name: DiscordServerStatus
version: '1.0'
main: org.goros.discordServerStatus.DiscordServerStatus
api-version: '1.21'
authors: [ Goros ]
description: Keep your Discord community connected to your Minecraft server! Discord Server Status is a lightweight plugin that links your Minecraft server with Discord, allowing your players to check server information directly from your Discord server.
